version: "3"
services:
  node-app:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes:
  postgres:
